### ISSUE TITLE
Story 1.1

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#1]
Als Chatbenutzer möchte ich eine strukturierte Webseite, damit ich eine schnelle Übersicht der Applikation habe.

**Tasks**
- [x] Leere Anwendung aufsetzen
- [x] Design festlegen
- [x] Header Bereich erstellen inkl. Styling
- [x] Footer Bereich erstellen inkl. Styling
- [x] Content Berech erstellen inkl. Styling
- [x] Header, Footer und Content Bereiche integrieren
- [x] Testing definieren, durchführen und dokumentieren

**Check List**
AK | &#10003;
--- | ---
AK1: Header, Footer und Content Bereich vorhanden
AK2: Aufteilung muss visuell ersichtlich sein durch Schwarze Linie
AK3: Hintergrund Header und Content Weiss #FFFFFF
AK4: Footer ist grau #A0A0A0
AK5: Sprache deutsch
AK6: Aufteilung im Verhältnis 1 - 3 - 1
AK7: Browser Chrome
