### ISSUE TITLE
Story 3.1

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#10]
Als Chatnutzer möchte ich ein History Feld sehen um zu sehen, was bisher im Chat kommuniziert wurde.

**Tasks**
- [x] Componente Content zu chat-bar anpassen
- [x] Neue Component "chat-history" erzeugen, als textarea (read only)
- [x] Ausgabefeld entfernen durch die chat-history ersetzen
- [x] Variable für Texteingabe wird im History Feld ganz unten dargestellt
- [x] Anpassung der Funktion vom Button "Absenden"
- [x] Event binding zwischen chat-bar Component und root Component
- [x] Property binding zwischen root Component und chat-history Component
- [x] Die ts "trim()" Funktion auf Message string Objekte anwenden

**Check List**
AK | &#10003;
--- | ---
AK1: Der neu eingegeben Text erscheint in einer neuen Zeile unter dem vorherigen Text im History Feld |
AK2: Feld ist über die ganze Breite |
AK3: History Feld muss scrollbar sein |
AK4: Trim Funktion funktioniert |
