### ISSUE TITLE
Story 4.1

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#14]
Als Chatbenutzer möchte ich die Nutzernamen vor der Textnachricht sehen, damit ich weiss, wer welche Nachricht geschrieben hat.

**Tasks**
- [x] neue Komponente "Login" erstellen
- [x] Darstellung der Gliederung der Komponenten
- [x] Eingabefeld für Loginname erstellen
- [x] Ausgabefeld mit Loginname erstellen
- [x] Button für Loginname übernehmen erstellen
- [x] Button speichert den Loginname im Ausgabefeld
- [x] Variable für Loginname festlegen, welcher links vom Text in der chat-History angezeigt wird.
- [x] Service "person" nutzen, um den Loginname in den Components verfügbar zu machen
- [x] Service "person" übergibt den Loginname in die chat-History
- [x] ts Methode "match()" erstellen zum Zeichenckeck für den Loginnamen
- [x] Funktion für Fehlermeldung ohne Loginname generieren und als alert ausgeben

**Check List**
AK | &#10003;
--- | ---
AK1: Login Komponente links vom Content Bereich | &#10003;
AK2: Eingabe-, Ausgabefeld und Button vorhanden | &#10003;
AK3: Loginname maximale Länge: 20 Zeichen | &#10003;
AK4: Loginname ist Pflichtfeld | &#10003;
AK5: Loginname Eingabe, Speichern und ändern | &#10003;
AK6: Loginname beginnen mit Buchstaben, können Zahlen enthalten, jedoch keine Sonderzeichen | &#10003;
AK7: Button heisst Bestätigen | &#10003;
AK8: Fehlermeldung, falls kein Loginname eingegeben wurde | &#10003;
AK9: Loginname steht links von der Chatnachricht | &#10003;
