### ISSUE TITLE
Story 3.2

### ISSUE THREAD

**Issue by SteeffiMo** [wannacryOST/SWL1easychat#16]
Als Chatbenutzer möchte ich eine Nachricht absenden, damit ich mit anderen Personen chatten kann. 

**Tasks**
- [x] Enter als Absende-Funktion hinzufügen
- [x] Button "Absenden" ist disabled
- [x] Eingabefeld in der Grösse nicht veränderbar machen

**Check List**
AK | &#10003;
--- | ---
AK1: Die Nachricht kann mit Enter abgeschickt werden. |
AK2: Das Feld "Absenden" kann nicht geklickt werden, wenn kein Text eingegeben wurde. |
AK3: Das Eingabefeld ist in der Grösse nicht veränderbar. |
