### ISSUE TITLE
Story 4.3

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#21]
Als Chatnutzer möchte ich die neuste Nachricht, auch mehrzeilig direkt sehen können, damit ich nicht zusätzlich runter scrollen muss.

**Tasks**
- [x] Neue Nachricht werden sofort sichtbar dargestellt ohne zu scrollen
- [x] Shift-Enter Taste erzeugt eine neue Zeile
- [x] Binding von Chat-Bar aus Chat-History lösen und in eigener Komponente anfügen

**Check List**
AK | &#10003;
--- | ---
AK1: Die Ansicht ist direkt bei der neusten Nachricht | &#10003;
AK2: Shift-Enter Taste generiert eine neue Zeile | &#10003;
AK3: Im History Feld hat es keine Textarea mehr | &#10003;
