### ISSUE TITLE
7.1 Login Name ändern

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#32]
Als Chatbenutzer möchte ich Änderungen des Login Namen als solche erkennen damit ich den Unterschied sehen, zwischen einer Änderung und eines neuen Chatnutzers, der beigetreten ist.

**Tasks**
- [x] Funktion erstellen, die prüft ob der Name vorher leer war oder bereits einen Wert hatte
- [x] Neuer Text ob neuer Benutzer beigetreten oder Änderung des Namens 
- [x] Login Name nach Eingabe für weitere Benutzer blockieren
- [x] Fehlermeldung generieren, falls der Name bereits vorhanden ist

**Check List**
AK | &#10003;
--- | ---
AK1: separate Nachricht für neuen Nutzernamen oder Änderung des Namens | &#10003;
AK2: Derselbe Name darf nicht zweimal verwendet werden | &#10003;
AK3: Login Name heisst neu | &#10003;
