### ISSUE TITLE
Story 7.2

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#33]
Als Chatnutzer möchte ich ein überarbeitetes Design, damit es schöner aussieht und der Text besser gelesen werden kann.

Fix aus Story 4 - 6

**Tasks**
- [x] Kontrast zwischen Text und Hintergrundfarbe erhöhen
- [x] Placeholder-Text von der Breite begrenzen
- [x] leerer Abschnitt unter der Login Komponente kleiner machen

**Check List**
AK | &#10003;
--- | ---
AK1: Text ist gut lesbar auf dem Hintergrund | &#10003;
AK2: Der Placeholder-Text kann nicht mehr über sein Inputfeld hinausgehen | &#10003;
AK3: Abstand zwischen Login und History Komponente sieht visuell gut aus | &#10003;
