### ISSUE TITLE
Story 6.3

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#34]
Als Chatbenutzer möchte ich im History Feld einen Time Stamp sehen, damit ich zu jeder Zeit weiss, wann eine Aktivität durchgeführt wurde.

**Tasks**
- [x] neues Objekt erstellen für die Zeitangabe
- [x] Zeitangabe bei History Ausgabe (in Array hinzufügen)
- [x] Anzeige bei der Ausgabe der Nachricht

**Check List**
AK | &#10003;
--- | ---
AK1: Zeitangabe bei jeder Ausgabe im History Feld | &#10003;
AK2: Zeitangabe in dd.mm.jjjj und hh:mm:ss | &#10003;
AK3: Position, Name: Zeitangabe und darunter die Message | &#10003;
AK4: Zeit soll eine kleine Schriftgrösse haben | &#10003;
