### ISSUE TITLE
7.7 Datum und Uhrzeit

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#42]
Als Chatbenutzer möchte ich bei einer Chatnachricht das Datum und die Uhrzeit sehen, bei Nachrichten von heute oder gestern statt das Datum Heute oder Gestern, damit ich sofort sehe, wann die Nachricht versendet wurde.

**Tasks**
- [ ] Timestamp unformatiert auf den Server laden
- [ ] Datumsformat auf dem Client verändern, sodass Monate ausgeschrieben werden ("Dezember" nicht 12)
- [ ] If Funktion auf dem Client ergänzen, dass bei einer Nachricht von Heute nur die Uhrzeit angezeigt wird und sonst das Datum und Uhrzeit.

**Check List**
AK | &#10003;
--- | ---
AK1: Das Datum hat das Format 7. Dezember 2021, 8:12 Uhr|
AK1: Nachrichten von heute haben das Format: Heute, 9:13 Uhr|
AK1: Nachrichten von gestern haben das Format: Gestern, 10:14 Uhr|
