### ISSUE TITLE
7.8 Server für mehrere Nutzer bereitstellen

### ISSUE THREAD

**Issue by KubiM3** [wannacryOST/SWL1easychat#44]
Als Chatbetreiber möchte ich einen Server aufsetzen, dass mehrere easyChat Benutzer miteinander chatten können, weil das der Zweck eines Chats ist. 

**Tasks**
- [x] Klasse "message" mit drei Attributen "message", "nickname", "date" generieren
- [x] neuen Service "chat" generieren
- [x] im Service "chat" http Requests importieren mit zwei Methoden "addToHistory" und "getHistory" als Observables
- [x] Service auf dem Server bereitstellen
- [x] URL erstellen

**Check List**
AK | &#10003;
--- | ---
AK1: Der Delay soll max. 2 sec. Betragen. | &#10003;
AK2: Die Stabilität des Systems ist gewährleistet. | &#10003;
AK3: Mehrere Benutzer können Messages austauschen | &#10003;
