### ISSUE TITLE
6.4.1 UX Design anpassen

### ISSUE THREAD

**Issue by SteeffiMo** [wannacryOST/SWL1easychat#45]
Als Chatbenutzer möchte ich ein Design, dass gemäss den Rückmeldungen der User angepasst ist, damit sich die Benutzerfreundlichkeit maximal erhöht.

**Tasks**
- [x] Text der Fehlermeldung, wenn Nickname fehlt, anpassen von "Bitte zuerst anmelden" auf "Bitte zuerst den Nicknamen eingeben"
- [x] Den Text "Willkommen" erst nach eingegebenem Nickname anzeigen lassen.
- [x] Grösse des Nickname-Eingabefelds und OK-Buttons analog dem Chat-bar-Eingabefelder bzw. Absende-Button anpassen.
- [x] Scrollbar in der Chat-History stylen
- [x] ÄÖÜ bzw. äöü bei der Eingabe vom Nickname erlauben

**Check List**
AK | &#10003;
--- | ---
AK1: Bei fehlendem Nickname lautet der Fehlertext "Bitte zuerst den Nicknamen eingeben" | &#10003;
AK2: Der Text "Willkommen" wird erst nach eingegebenem Nickname angezeigt. | &#10003;
AK3: Die Eingabefelder und die Buttons sind in der Mobile-Ansicht gleich gross. | &#10003;
AK4: Die Scrollbar ist an das restliche Design angepasst. | &#10003;
AK5: Die Nickname-Eingabe erlaubt auch ÄÖÜ bzw. äöü. | &#10003;
