### ISSUE TITLE
8.2 Cloud

### ISSUE THREAD

**Issue by SteeffiMo** [wannacryOST/SWL1easychat#49]
Als Chatbenutzer möchte ich meine Chat-App vollständig in der Cloud haben, damit ich über eine URL auf den Chat zugreifen kann und mit anderen chatten kann.

**Tasks**
- [x] Recherche
- [x] Heroku-Server mit Angular-Projekt verbinden
- [ ] Security-Aspekte mit Cors einbinden gemäss Anleitung siehe Folie
- [x] URL in der Dokumentation einfügen

**Check List**
AK | &#10003;
--- | ---
AK1: Angular-Web-App läuft in der Cloud. |
AK2: Heroku-App ist erstellt. |
AK3: Die URL ist aufrufbar. |
