### ISSUE TITLE
8.3 Liste aktive Users

### ISSUE THREAD

**Issue by SteeffiMo** [wannacryOST/SWL1easychat#50]
Als Chatbenutzer möchte ich die aktuell aktiven User in einer eigenen Liste sehen, damit ich weiss, mit wem ich alles chatten kann.

**Tasks**
- [x] Komponente users erstellen
- [x] in Users-Komponente Liste definieren
- [x] über pService aktuelle Users vom Server abrufen
- [x] Funktion schreiben, die aktuelle Users in der Liste ausgibt
- [ ] if-Funktion ergänzen, damit neue User hinzugefügt werden und geänderte Namen nur der Name aktualisiert wird
- [x] Liste so ausgeben, damit neuste Users zu oberst erscheinen

**Check List**
AK | &#10003;
--- | ---
AK1: Die aktiven User werden separat in einer Liste angezeigt |
AK2: Namen werden dynamisch angepasst. |
AK3: die neusten User werden zu oberst dargestellt. |
AK4: Inaktive Nutzer werden gelöscht. |
