### ISSUE TITLE
8.4 Fixes aus Sprint 7

### ISSUE THREAD

**Issue by SteeffiMo** [wannacryOST/SWL1easychat#51]
Als Chatbenutzer möchte ich ein angepasstes Design und grösseres Array damit das chatten angenehmer ist. 

**Tasks**
- [x] Verhältnis 1:3:1 ändern auf optimales Design.
- [x] Chat-History automatisch nach unten scrollen 
- [ ] Maximale Anzahl von 20 Messages in Array erweitern auf 999 Messages.

**Check List**
AK | &#10003;
--- | ---
AK1: Bei maximaler Fenstergrösse ist kein scrollen notwendig. |
AK2: Die Chat-History scrollt immer automatisch nach unten. |
AK3: Es können 999 Nachrichten eingegeben werden und die 1'000. Nachricht wird gelöscht. |
