### ISSUE TITLE
9.1 Chat-Design

### ISSUE THREAD

**Issue by SteeffiMo** [wannacryOST/SWL1easychat#55]
Als Chatbenutzer möchte ich meine Nachrichten rechtsbündig und die anderen Nachrichten linksbündig sehen, damit die Kommunikation einfacher ersichtlich ist.

**Tasks**
- [ ] eigene Nachrichten von fremden Nachrichten im Code unterscheiden
- [ ] Styling anpassen, damit eigene Nachrichten rechtsbündig dargestellt werden
- [ ] Styling anpassen, damit Infomessages ("ist dem Chat beigetreten" + "hat den Namen geändert auf" mittig dargestellt werden

**Check List**
AK | &#10003;
--- | ---
AK1: Die eigenen Nachrichten werden rechtsbündig dargestellt. |
AK2: Die fremden Nachrichten werden linksbündig dargestellt. |
AK3: Die Infomessages werden mittig dargestellt. |
